max_epochs: ${constants.max_epochs}
max_steps: ${constants.max_steps}
max_train_steps_per_epoch: ${constants.max_train_steps_per_epoch}

checkpoint_every_n_steps: ${constants.checkpoint_every_n_steps}

resume_from_last_ckpt: True
model_entity_id: null
model_store_checkpoint_version: null
garbage_collector_interval: 5001
pretrained_weights: null
log_dir: manifold://fblearner_flow_run_metrics/tree/torchmultimodal/idm_vton/logs
use_pt2: False
memory_snapshot: False
