# File used for running pure prediction with torchtnt, including a custom score computation.

seed: 42

defaults:
  - constants: base
  # - model: idm_vton_sd15
  # - model: idm_vton_sdxl
  # - model: cat_vton_sd15
  # - model: cat_vton_sdxl
  - model: simple_vton_sd15
  # - model: simple_vton_sdxl
  # - model: simple_vton_sd15_fluxvae
  # - model: simple_vton_sdxl_fluxvae
  - datasets:
    - viton_hd_test
    - dress_code_test
    - deepfashion_test
  - _self_

constants:
  # for virtual try-on
  # height: 512
  # width: 384
  height: 1024
  width: 768
  # for pose transfer
  # height: 256
  # width: 176
  # height: 512
  # width: 352
  # height: 1024
  # width: 704
  batch_size: 1

# null to go through whole dataloader.
max_steps_per_epoch: null
dataloader: ${datasets.viton_hd_test.dataloader}
# dataloader: ${datasets.dress_code_test.dataloader}
# dataloader: ${datasets.deepfashion_test.dataloader}
manifold_log_dir: manifold://genads_models/tree/zijianzhou/output/simple_vton/tmp

inference:
  # _target_: leffa.inference.IdmVtonInference
  # _target_: leffa.inference.CatVtonInference
  _target_: leffa.inference.SimpleVtonInference
  _partial_: True
  model: ${model}
  model_entity_id: null
  checkpoint_version: null

callbacks:
  - _target_: leffa.callbacks.save_image_callback.SaveImageCallback
    manifold_path: ${manifold_log_dir}/generated_paired
    # manifold_path: ${manifold_log_dir}/generated_unpaired
    task_type: vton
    # manifold_path: ${manifold_log_dir}
    # task_type: pose_transfer

unit:
  _target_: leffa.vton_pred_unit.VtonPredUnit
  inference_fn: ${inference}

hydra:
  run:
    dir: /tmp/
