viton_hd_test_local:
  dataset:
    _target_: leffa.datasets.viton_hd.VitonHDLocalDataset
    # _target_: leffa.datasets.random_dataset.RandomDataset
    dataroot_path: /home/zijianzhou/data/viton_hd
    phase: test
    order: unpaired
    size:
      - ${constants.height}
      - ${constants.width}

  dataloader:
    _target_: torch.utils.data.DataLoader
    dataset: ${datasets.viton_hd_test_local.dataset}
    batch_size: ${constants.batch_size}
    num_workers: 0
    prefetch_factor: null
    pin_memory: true
    persistent_workers: false
    multiprocessing_context: null
