_target_: leffa.models.cat_vton_model.CatVtonModel
# SDXL
pretrained_model_name_or_path: manifold://genads_models/tree/zijianzhou/model/stable-diffusion-xl-1.0-inpainting-0.1
new_in_channels: 9
height: ${constants.height}
width: ${constants.width}
garment_dropout_ratio: 0.1
use_dream: true
dream_detail_preservation: 10.0
use_garment_mask: false
only_optimize_unet_attn1: false
