_target_: leffa.models.cat_vton_model.CatVtonModel
# SD1.5
pretrained_model_name_or_path: manifold://genads_models/tree/zijianzhou/model/stable-diffusion-inpainting
pretrained_vae_name_or_path: manifold://genads_models/tree/zijianzhou/model/sd-vae-ft-mse
new_in_channels: 9
height: ${constants.height}
width: ${constants.width}
garment_dropout_ratio: 0.1
use_dream: true
dream_detail_preservation: 10.0
use_garment_mask: false
only_optimize_unet_attn1: true
use_learning_flow_in_attention: false
learning_flow_in_attention_lambda: 0.001
learning_flow_in_attention_stop_timestep: 500
use_attention_flow_loss: false
attention_flow_loss_lambda: 0.001
use_pixel_space_supervision: true
pixel_space_supervision_lambda: 10.0
use_densepose: false
