_target_: leffa.models.idm_vton_model.IdmVtonModel
pretrained_model_name_or_path: manifold://genads_models/tree/zijianzhou/model/stable-diffusion-xl-1.0-inpainting-0.1
pretrained_garmentnet_path: manifold://genads_models/tree/zijianzhou/model/stable-diffusion-xl-base-1.0
pretrained_image_encoder_path: manifold://genads_models/tree/zijianzhou/model/IP-Adapter/models/image_encoder
pretrained_ip_adapter_path: manifold://genads_models/tree/zijianzhou/model/IP-Adapter/sdxl_models/ip-adapter-plus_sdxl_vit-h.bin
new_in_channels: 13
height: ${constants.height}
width: ${constants.width}
garment_dropout_ratio: 0.1
use_dream: false
dream_detail_preservation: 10.0
skip_cross_attention: false
skip_cross_attention_garmentnet: false
copy_unet_to_unet_encoder: false
only_optimize_unet_attn1: false
optimize_unet: true
optimize_unet_encoder: false
