_target_: leffa.models.simple_vton_model.SimpleVtonModel
pretrained_model_name_or_path: manifold://genads_models/tree/zijianzhou/model/stable-diffusion-inpainting
pretrained_vae_name_or_path: manifold://genads_models/tree/zijianzhou/model/sd-vae-ft-mse
pretrained_garmentnet_path: manifold://genads_models/tree/zijianzhou/model/stable-diffusion-inpainting
new_in_channels: 12
height: ${constants.height}
width: ${constants.width}
garment_dropout_ratio: 0.1
use_dream: false
dream_detail_preservation: 10.0
skip_cross_attention: true
skip_cross_attention_garmentnet: true
copy_unet_to_unet_encoder: false
only_optimize_unet_attn1: false
optimize_unet: true
optimize_unet_encoder: true
use_learning_flow_in_attention: false
learning_flow_in_attention_lambda: 0.001
learning_flow_in_attention_stop_timestep: 500
use_attention_flow_loss: false
attention_flow_loss_lambda: 0.001
use_pixel_space_supervision: false
pixel_space_supervision_lambda: 10.0
