# for virtual try-on
# height: 512
# width: 384
# batch_size: 8
height: 1024
width: 768
batch_size: 2

# for pose transfer
# height: 256
# width: 176
# batch_size: 8
# height: 512
# width: 352
# batch_size: 4
# height: 1024
# width: 704
# batch_size: 1

precision: bf16

max_steps: null
max_epochs: 200
max_train_steps_per_epoch: null

evaluate_every_n_train_steps: null
evaluate_every_n_train_epochs: null
max_eval_steps_per_eval_epoch: null

use_torchsnapshot: false
checkpoint_every_n_steps: 500
